### ISSUE TITLE
Incorrect ordering when set is used to create Set

### ISSUE THREAD

**Issue by Chipe1** [neuml/py27hash#2]
Steps to reproduce
```
from py27hash.set import Set
s1 = Set([2, 3, 4, 5, 8])  # init using list
s2 = Set({2, 3, 4, 5, 8})  # init using set
print(list(s1), list(s2)) # order should be same, but it's not
```

**Comment by davidmezzetti** [comment]
Thank you for submitting this issue and sorry for the long delay in responding. Happy to accept pull requests if you have a solution to this. Other efforts have taken priority over py27hash.

**Comment by davidmezzetti** [comment]
Thank you for submitting this issue and sorry for the long delay in responding. Happy to accept pull requests if you have a solution to this. Otherwise I'll keep this open and address next time py27hash has a new release.

**Comment by davidmezzetti** [comment]
Thank you for submitting this issue and sorry for the long delay in responding. Happy to accept pull requests if you have a solution to this. Otherwise, I'll keep this open and address next time py27hash has a new release.

**Comment by musicinmybrain** [comment]
It seems to me that dicts behave the same way:

```
from py27hash.dict import Dict
d1 = Dict([(2, "a"), (3, "b"), (4, "c"), (5, "d"), (8, "e")])
d2 = Dict({2: "a", 3: "b", 4: "c", 5: "d", 8: "e"})
print(list(d1.items()), list(d2.items()))
```
